### PR TITLE
moves 'relays' to 'relays get' and implements looking up a specific list of relays as 'relays find'

### LINKED ISSUE #188: Want to list specific relay
Currently, the `conch relays` command lists all relays which are or have registered with the Conch API server. As this list grows long over time as new relays are added, it would be handy to be able to specify a specific relay (or relays) to list. I propose that `conch relays` take an optional argument list of relay IDs, such as:

```
$ conch relays ams-drd1 tpe-drd2 ...
```

and the resulting output would be limited to those IDs.

### PR DESCRIPTION
**Pull request by sungo**
```
conch relays get
conch relays find my-drd-1 my-drd-12
```

Closes #188

### CODE REVIEW

**Comment by daleghent** [comment]
This is a good change and I think sets the command line structure up for future relay-related stuff like `set`s of things. Question about `find`, though. From looking at the implementation, it's a literal string match? When I use `conch rs` now, it's usually in combination with `grep` and some substring... like if I want to find all the eu-central relays, I do: `conch rs | grep eu-central`. Would it be hard to have the argument to `find` be a regex?

**Comment by sungo** [comment]
#188 asked for listing specific relays. I'll look into making the parameters into regexps

**Comment by daleghent** [comment]
Ah I see. Well, I think #188 was made when we had comparatively fewer relays than we do now, and so the sifting needs to be a bit more flexible as a result.

**Comment by sungo** [comment]
No worries. I'll get it sorted in a bit

**Comment by sungo** [comment]
Updated as requested. New syntax is as follows:

```
Usage: conch relays find [OPTIONS] RELAYS...                                                                                                                                                         
                                                                                                                                                                                                     
                                                                                                                                                                                                     
Takes a list of regular expressions and matches those against the IDs of all known relays.                                                                                                           
                                                                                                                                                                                                     
The default behavior is to match as a logical OR but this behavior can be changed by providing the --and flag                                                                                        
                                                                                                                                                                                                     
For instance:                                                                                                                                                                                        
                                                                                                                                                                                                     
* "conch relay find drd" will find all relays with 'drd' in their ID. For perl folks, this is essentially 'm/drd/'                                                                                   
* "conch relay find '^ams-'" will find all relays with IDs that begin with 'ams-'                                                                                                                    
* "conch relay find drd '^ams-' will find all relays with IDs that contain 'drd' OR begin with 'ams-'                                                                                                
* "conch relay find --and drd '^ams-' will find all relays with IDs that contain 'drd' AND begin with '^ams-'                                                                                        
                                                                                                                                                                                                     
Arguments:                                                                                                                                                                                           
  RELAYS       List of regular expressions to match against relay IDs                                                                                                                                
                                                                                                                                                                                                     
Options:                                                                                                                                                                                             
      --and    Match the list as a logical AND
```

**Pull request merged**
